name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_MAIL_FROM_FORM: ${{ secrets.REACT_APP_MAIL_FROM_FORM }}
        REACT_APP_RECAPTCHA_SITE_KEY: ${{ secrets.REACT_APP_RECAPTCHA_SITE_KEY }}
        RECAPTCHA_SITE_SECRET: ${{ secrets.RECAPTCHA_SITE_SECRET }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
